on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  build:
    name: Prebuild & Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  
        uses: actions/checkout@v5.0.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Expo CLI
        run: npm install -g expo-cli
        
      - name: Install dependencies
        working-directory: ./react-native-app
        run: npm install

      - name: Expo Prebuild (Android only)
        working-directory: ./react-native-app
        run: npx expo prebuild --platform android --no-install

      - name: Make gradlew executable
        run: chmod +x ./react-native-app/android/gradlew

      - name: Build APK
        working-directory: ./react-native-app/android
        run: ./gradlew assembleRelease
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ./react-native-app/android/app/build/outputs/apk/release/app-release.apk

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Create GitHub Release and Upload APK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="release-$(date +'%Y%m%d%H%M%S')"
          APK_PATH="./react-native-app/android/app/build/outputs/apk/release/app-release.apk"
          
          # Create a release with a unique timestamp-based tag
          gh release create "$TAG" "$APK_PATH" \
            --title "Automated Release $TAG" \
            --notes "This is an automated release with the built APK."

