on:
  push:
    branches:
    - trying-actions

jobs:
  build:
    name: Prebuild & Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install project dependencies
        run: npm install

      - name: Expo Prebuild (Android only)
        run: npx expo prebuild --platform android --no-install

      - name: Make gradlew executable
        run: chmod +x ./android/gradlew

      - name: Build APK
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
